name: sparse-inputs
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - h5py
  - scikit-learn
  - matplotlib
  - seaborn
  - joblib
  - tqdm
  - jupyter
  - ipykernel
  - nbconvert
  - pip
